import ThemeRegistry from '@/components/ThemeRegistry'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Remotion',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: ReactNode
}) {
    return (
        <html lang="en">
            <body
                style={{
                    minHeight: '100dvh',
                }}
            >
                <ThemeRegistry>{children}</ThemeRegistry>
            </body>
        </html>
    )
}
